### ISSUE TITLE
Correção Exercício `0.9.1`

### ISSUE THREAD

**Issue by mathiasgheno** [gabydian/0.9.1#1]
# Correção Exercício `0.9.1`

> Adapte o [exercício ](https://github.com/5f66103209de4c0fa14caf9345a6f291?pvs=25)da aula anterior (exercício [0.8.1](https://github.com/5f66103209de4c0fa14caf9345a6f291?pvs=25)) e crie um botão de fechar semelhante com o apresentado no wireframe abaixo. A cor de background do botão deve mudar quando ocorrer o evento de hover. Utilize [esse ícone](https://fontawesome.com/icons/xmark?f=classic&s=solid).

**Nota:** 10! Parabéns 🥳 

# Comentários

Para fazer com que o seu botão tenha uma centralização horizontal e vertical 100% você pode fazer uso do display flex e de uma altura e largura fixa. Veja o exemplo abaixo. 

```css
.fechar {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 30px;
    width: 30px;
}
```

[^1]: [Snake Case VS Camel Case VS Pascal Case VS Kebab Case – What's the Difference Between Casings?](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/)
